version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: docker.dev
    container_name: dev_container
  Stage:
    build:
      context: .
      dockerfile: docker.stage
    container_name: stage_container
  Prod:
    build:
      context: .
      dockerfile: docker.prod
    container_name: prod_container



# how to download docker-compse

# https://github.com/docker/compose/releases/tag/v2.29.0 -- select linux at bottom