apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod1
  name: testpod1
spec:
  containers:
  - image: nginx
    name: testpod1


#without creating any file you can directly copy & paste above code in linux by placing "echo" command

echo 'apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod1
  name: testpod1
spec:
  containers:
  - image: nginx
    name: testpod1' | kubectl run -f -






    