#to secure the pod from failure/termination/deletion 

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: app
        image: sreeharshav/rollingupdate:v1

#linux command to split screen
tmux --> ctrl b + shift "  (you will see 2 windows in 1 screen)
#how to move the cursor in this case 
ctrl v + up arrow / ctrl v + down arrow
